python ProjectCreator.py roadsigns jp_roadsigns  JP_RoadSigns_90classes
python ProjectCreator.py roadsigns us_roadsigns  US_RoadSigns_86classes
python ProjectCreator.py roadsigns us_roadsigns  US_RoadSigns_160classes
python ProjectCreator.py roadsigns uk_roadsigns  UK_RoadSigns_94classes
python ProjectCreator.py roadsigns fr_roadsigns  FR_RoadSigns_152classes
